### ISSUE TITLE
Replace `kaminari`

### ISSUE THREAD

**Issue by cs** [shore-gmbh/sinatra-template#9]
I propose that we replace `kaminari` with a different pagination solution.

Why replace it? Due to `kaminari`s dependence on `actionpack` we are adding a huge number unneeded dependencies. I would prefer to keep the template as light-weight as possible.

@rudionrails Would you be open to discuss alternative pagination solutions?

**Comment by rudionrails** [comment]
So, you are looking to replace it or remove it?

**Comment by cs** [comment]
We should probably keep some kind pagination in the template, simply because it's a very common requirement. So, I would say **replace it**.

**Comment by rudionrails** [comment]
OK, with what would you replace it then? I still think kaminari is very kommon and really nice to extend, but I understand the problem that it pulls actionpack into the source (don't know why this is needed in the first place). What alternatives do we have?
